
// OPEC countries list due to no trusted api available

// result generated by web

export const OPEC_COUNTRIES = [
  'Algeria',
  'Congo',
  'Equatorial Guinea',
  'Gabon',
  'Iran',
  'Iraq',
  'Kuwait',
  'Libya',
  'Nigeria',
  'Saudi Arabia',
  'United Arab Emirates',
  'Venezuela',
];